import { Tool } from "@/types"

export const tools: Tool[] = [
  {
    slug: "jasper-ai",
    name: "Jasper AI",
    tagline: "The AI writing assistant built for marketing teams",
    description: "Jasper is an AI content platform that helps marketing teams create high-quality content at scale. From blog posts to ad copy, Jasper produces on-brand content 10x faster than writing from scratch.",
    logo: "J",
    category: "AI Writing",
    pricing: {
      free: false,
      startingAt: "$39/mo",
      plans: [
        { name: "Creator", price: "$39/mo", features: ["1 user", "1 Brand Voice", "50+ templates", "SEO mode"] },
        { name: "Pro", price: "$59/mo", features: ["5 users", "3 Brand Voices", "Collaboration", "Campaigns"] },
        { name: "Business", price: "Custom", features: ["Unlimited users", "Custom AI", "SSO", "Dedicated support"] },
      ],
    },
    rating: 4.7,
    reviewCount: 2847,
    pros: ["Exceptional output quality", "Huge template library", "Great for teams", "Brand voice training", "Integrates with Surfer SEO"],
    cons: ["No free plan", "Can be pricey for solos", "Occasional factual errors", "Learning curve for advanced features"],
    affiliateUrl: "https://jasper.ai?ref=aitoolsreview",
    affiliateCommission: "30% recurring",
    websiteUrl: "https://jasper.ai",
    features: ["50+ content templates", "Brand Voice", "SEO mode", "Plagiarism checker", "Chrome extension", "API access"],
    bestFor: ["Marketing teams", "Content agencies", "E-commerce brands", "SEO professionals"],
    badge: "Top Pick",
  },
  {
    slug: "surfer-seo",
    name: "Surfer SEO",
    tagline: "Rank higher with data-driven content optimization",
    description: "Surfer SEO analyzes top-ranking pages and tells you exactly what to write to rank on Google. It combines AI writing with real-time SERP data for content that actually ranks.",
    logo: "S",
    category: "SEO Tools",
    pricing: {
      free: false,
      startingAt: "$89/mo",
      plans: [
        { name: "Essential", price: "$89/mo", features: ["30 articles/mo", "Content Editor", "Keyword Research"] },
        { name: "Scale", price: "$129/mo", features: ["100 articles/mo", "AI writing", "Audit tool"] },
        { name: "Enterprise", price: "Custom", features: ["Unlimited", "White label", "API", "Dedicated CSM"] },
      ],
    },
    rating: 4.8,
    reviewCount: 1923,
    pros: ["Best-in-class SERP analysis", "Real-time optimization score", "Keyword research built in", "Jasper integration", "Clear actionable guidance"],
    cons: ["Expensive for small sites", "No free plan", "Data can lag", "Limited to content SEO"],
    affiliateUrl: "https://surferseo.com?ref=aitoolsreview",
    affiliateCommission: "25% recurring",
    websiteUrl: "https://surferseo.com",
    features: ["Content Editor", "SERP Analyzer", "Keyword Research", "Site Audit", "AI Outline", "NLP optimization"],
    bestFor: ["SEO professionals", "Content marketers", "Agencies", "Bloggers serious about ranking"],
    badge: "Best for SEO",
  },
  {
    slug: "writesonic",
    name: "Writesonic",
    tagline: "AI writing for everyone — free plan included",
    description: "Writesonic is one of the most capable AI writing tools with a generous free plan. It powers everything from blog posts to landing pages, product descriptions, and ads using GPT-4.",
    logo: "W",
    category: "AI Writing",
    pricing: {
      free: true,
      startingAt: "$16/mo",
      plans: [
        { name: "Free", price: "$0", features: ["10k words/mo", "ChatSonic", "100+ templates"] },
        { name: "Small Team", price: "$16/mo", features: ["Unlimited words", "GPT-4", "Brand Voice"] },
        { name: "Enterprise", price: "Custom", features: ["Custom AI", "SSO", "Dedicated support"] },
      ],
    },
    rating: 4.5,
    reviewCount: 3241,
    pros: ["Generous free plan", "GPT-4 powered", "100+ templates", "ChatSonic included", "Affordable entry price"],
    cons: ["Quality varies by template", "Word limits on free", "UI can feel cluttered", "Less precise than Jasper"],
    affiliateUrl: "https://writesonic.com?ref=aitoolsreview",
    affiliateCommission: "30% recurring",
    websiteUrl: "https://writesonic.com",
    features: ["100+ templates", "ChatSonic AI", "Brand Voice", "Bulk generation", "Zapier integration", "API"],
    bestFor: ["Freelancers", "Small businesses", "Solopreneurs", "Budget-conscious marketers"],
    badge: "Best Free Plan",
  },
  {
    slug: "copy-ai",
    name: "Copy.ai",
    tagline: "Go from prompt to pipeline with AI",
    description: "Copy.ai has evolved from a copywriting tool into a full GTM AI platform. It automates sales, marketing, and content workflows with AI — from cold emails to full campaign execution.",
    logo: "C",
    category: "AI Writing",
    pricing: {
      free: true,
      startingAt: "$36/mo",
      plans: [
        { name: "Free", price: "$0", features: ["2,000 words/mo", "90+ tools", "Chat"] },
        { name: "Pro", price: "$36/mo", features: ["Unlimited words", "5 users", "Workflows"] },
        { name: "Team", price: "$186/mo", features: ["20 users", "Advanced workflows", "API"] },
      ],
    },
    rating: 4.4,
    reviewCount: 2156,
    pros: ["Excellent free plan", "90+ copywriting tools", "Workflow automation", "Great for cold outreach", "Active community"],
    cons: ["Workflow learning curve", "Less polished than Jasper", "Inconsistent quality", "Limited SEO features"],
    affiliateUrl: "https://copy.ai?ref=aitoolsreview",
    affiliateCommission: "$50–$100 per referral",
    websiteUrl: "https://copy.ai",
    features: ["90+ AI tools", "Workflows", "Chat interface", "Bulk processing", "API access", "Integrations"],
    bestFor: ["Sales teams", "Marketing ops", "Cold email writers", "Startups"],
  },
  {
    slug: "pictory",
    name: "Pictory",
    tagline: "Turn text and scripts into professional videos instantly",
    description: "Pictory uses AI to transform blog posts, scripts, and long-form content into short branded videos. Perfect for repurposing content without any video editing experience.",
    logo: "P",
    category: "AI Video",
    pricing: {
      free: false,
      startingAt: "$19/mo",
      plans: [
        { name: "Starter", price: "$19/mo", features: ["30 videos/mo", "Text to video", "1080p export"] },
        { name: "Professional", price: "$39/mo", features: ["60 videos/mo", "Branded templates", "Highlight reel"] },
        { name: "Teams", price: "$99/mo", features: ["3 workspaces", "Unlimited brands", "Priority support"] },
      ],
    },
    rating: 4.3,
    reviewCount: 987,
    pros: ["No video editing skills needed", "Great for repurposing content", "Auto captions", "Stock library included", "Affordable"],
    cons: ["Limited customization", "AI voice sounds robotic", "No live action recording", "Export speed can be slow"],
    affiliateUrl: "https://pictory.ai?ref=aitoolsreview",
    affiliateCommission: "20% recurring",
    websiteUrl: "https://pictory.ai",
    features: ["Text to video", "Blog to video", "Auto captions", "Stock media library", "Brand kit", "Script to video"],
    bestFor: ["Content repurposers", "Social media managers", "Coaches", "Course creators"],
  },
  {
    slug: "synthesia",
    name: "Synthesia",
    tagline: "Create AI videos with human avatars in minutes",
    description: "Synthesia lets you create professional videos with realistic AI avatars and voices in 130+ languages — no camera, no studio, no actors needed. Used by 50,000+ companies including Google and Reuters.",
    logo: "SY",
    category: "AI Video",
    pricing: {
      free: false,
      startingAt: "$29/mo",
      plans: [
        { name: "Starter", price: "$29/mo", features: ["10 videos/mo", "90+ avatars", "60+ templates"] },
        { name: "Creator", price: "$89/mo", features: ["30 videos/mo", "Custom avatar", "Screen recorder"] },
        { name: "Enterprise", price: "Custom", features: ["Unlimited", "API", "SSO", "Custom avatars"] },
      ],
    },
    rating: 4.6,
    reviewCount: 1456,
    pros: ["Most realistic AI avatars", "130+ languages", "No filming needed", "Professional output", "Enterprise ready"],
    cons: ["Expensive for high volume", "Avatars can look uncanny", "No free plan", "Limited B-roll options"],
    affiliateUrl: "https://synthesia.io?ref=aitoolsreview",
    affiliateCommission: "20–30% per sale",
    websiteUrl: "https://synthesia.io",
    features: ["160+ AI avatars", "130+ languages", "Custom avatar", "Screen recorder", "API", "Brand kit"],
    bestFor: ["L&D teams", "Corporate training", "Explainer videos", "Multilingual content"],
    badge: "Best AI Avatars",
  },
  {
    slug: "descript",
    name: "Descript",
    tagline: "Edit video by editing text — the future of post-production",
    description: "Descript transcribes your video and lets you edit it like a document. Delete filler words, clone your voice, remove silences, and publish — all without touching a traditional timeline editor.",
    logo: "D",
    category: "AI Video",
    pricing: {
      free: true,
      startingAt: "$24/mo",
      plans: [
        { name: "Free", price: "$0", features: ["1 transcription hr/mo", "Basic editing", "720p export"] },
        { name: "Creator", price: "$24/mo", features: ["10 hrs/mo", "AI features", "4K export"] },
        { name: "Business", price: "$40/mo", features: ["Unlimited", "Team features", "Priority support"] },
      ],
    },
    rating: 4.7,
    reviewCount: 2034,
    pros: ["Revolutionary editing workflow", "Best-in-class transcription", "Filler word removal", "Voice clone", "Great for podcasts"],
    cons: ["Resource intensive", "Collaboration can lag", "Learning curve", "Some AI features hit or miss"],
    affiliateUrl: "https://descript.com?ref=aitoolsreview",
    affiliateCommission: "15–20% recurring",
    websiteUrl: "https://descript.com",
    features: ["Text-based editing", "AI transcription", "Filler word removal", "Overdub voice clone", "Screen recording", "Podcast publishing"],
    bestFor: ["Podcasters", "YouTubers", "Video editors", "Content creators"],
  },
  {
    slug: "canva-pro",
    name: "Canva Pro",
    tagline: "Design anything. Publish anywhere.",
    description: "Canva Pro supercharges the world's most popular design tool with AI features, brand kits, unlimited storage, background remover, and thousands of premium templates. The go-to design tool for non-designers.",
    logo: "CA",
    category: "AI Design",
    pricing: {
      free: true,
      startingAt: "$15/mo",
      plans: [
        { name: "Free", price: "$0", features: ["250,000+ templates", "5GB storage", "Basic tools"] },
        { name: "Pro", price: "$15/mo", features: ["100M+ assets", "Brand Kit", "Background remover", "Magic Resize"] },
        { name: "Teams", price: "$10/mo/user", features: ["All Pro features", "Collaboration", "Admin controls"] },
      ],
    },
    rating: 4.8,
    reviewCount: 8923,
    pros: ["Incredibly easy to use", "Massive template library", "AI image generation", "Brand Kit", "Best value in design"],
    cons: ["Not for professional designers", "Limited typography control", "Exports can compress quality", "AI features still maturing"],
    affiliateUrl: "https://canva.com?ref=aitoolsreview",
    affiliateCommission: "Up to $36 per subscription",
    websiteUrl: "https://canva.com",
    features: ["Magic Write AI", "Text to Image", "Background Remover", "Magic Resize", "Brand Kit", "100M+ assets"],
    bestFor: ["Small businesses", "Social media managers", "Non-designers", "Marketers", "Educators"],
    badge: "Most Popular",
  },
  {
    slug: "grammarly",
    name: "Grammarly",
    tagline: "Write with confidence — grammar, style, and tone in one",
    description: "Grammarly is the world's leading AI writing assistant, helping 30 million people write clearer, mistake-free content. From emails to essays, it catches errors and suggests improvements in real time across every platform.",
    logo: "G",
    category: "AI Writing",
    pricing: {
      free: true,
      startingAt: "$12/mo",
      plans: [
        { name: "Free", price: "$0", features: ["Grammar checks", "Spelling", "Basic tone"] },
        { name: "Premium", price: "$12/mo", features: ["Style suggestions", "Plagiarism checker", "Full-sentence rewrites"] },
        { name: "Business", price: "$15/mo/user", features: ["Team dashboard", "Style guide", "Analytics"] },
      ],
    },
    rating: 4.6,
    reviewCount: 12847,
    pros: ["Works everywhere", "Excellent free plan", "Real-time suggestions", "Tone detection", "Plagiarism checker in Premium"],
    cons: ["Premium needed for full value", "Can over-suggest changes", "Privacy concerns for sensitive docs", "Occasional false positives"],
    affiliateUrl: "https://grammarly.com?ref=aitoolsreview",
    affiliateCommission: "$0.20 free / $20 premium signup",
    websiteUrl: "https://grammarly.com",
    features: ["Grammar & spelling", "Style suggestions", "Tone detector", "Plagiarism checker", "Full rewrites", "Works everywhere"],
    bestFor: ["Students", "Professionals", "Non-native English speakers", "Anyone who writes"],
    badge: "Editor's Choice",
  },
  {
    slug: "hostinger",
    name: "Hostinger",
    tagline: "Fast, affordable hosting powered by AI website builder",
    description: "Hostinger offers blazing-fast web hosting with an AI website builder that creates a professional site in minutes. At $2.99/mo it's the best value hosting on the market, backed by 24/7 support.",
    logo: "H",
    category: "Web Hosting",
    pricing: {
      free: false,
      startingAt: "$2.99/mo",
      plans: [
        { name: "Premium", price: "$2.99/mo", features: ["100 websites", "100GB SSD", "Free domain", "SSL"] },
        { name: "Business", price: "$3.99/mo", features: ["200GB SSD", "Daily backups", "CDN"] },
        { name: "Cloud", price: "$9.99/mo", features: ["300GB SSD", "Dedicated resources", "Priority support"] },
      ],
    },
    rating: 4.5,
    reviewCount: 6234,
    pros: ["Cheapest quality hosting", "AI website builder", "Free domain included", "Fast load times", "24/7 live chat"],
    cons: ["Renewal prices higher", "No US data center on cheapest plan", "Limited staging environment", "Phone support not available"],
    affiliateUrl: "https://hostinger.com?ref=aitoolsreview",
    affiliateCommission: "60% per sale",
    websiteUrl: "https://hostinger.com",
    features: ["AI Website Builder", "Free domain", "Free SSL", "LiteSpeed servers", "WordPress one-click", "99.9% uptime"],
    bestFor: ["Beginners", "Small businesses", "Bloggers", "Budget-conscious site owners"],
  },
]

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug)
}

export function getToolsByCategory(category: string): Tool[] {
  return tools.filter((t) => t.category === category)
}

export const categories = [...new Set(tools.map((t) => t.category))]
