import { Tool } from "@/types"

export const tools: Tool[] = [
  {
    slug: "jasper-ai",
    name: "Jasper AI",
    tagline: "The AI writing assistant built for marketing teams",
    description: "Jasper is an AI content platform that helps marketing teams create high-quality content at scale. From blog posts to ad copy, Jasper produces on-brand content 10x faster than writing from scratch.",
    logo: "J",
    category: "AI Writing",
    pricing: {
      free: false,
      startingAt: "$39/mo",
      plans: [
        { name: "Creator", price: "$39/mo", features: ["1 user", "1 Brand Voice", "50+ templates", "SEO mode"] },
        { name: "Pro", price: "$59/mo", features: ["5 users", "3 Brand Voices", "Collaboration", "Campaigns"] },
        { name: "Business", price: "Custom", features: ["Unlimited users", "Custom AI", "SSO", "Dedicated support"] },
      ],
    },
    rating: 4.7,
    reviewCount: 2847,
    pros: ["Exceptional output quality", "Huge template library", "Great for teams", "Brand voice training", "Integrates with Surfer SEO"],
    cons: ["No free plan", "Can be pricey for solos", "Occasional factual errors", "Learning curve for advanced features"],
    affiliateUrl: "https://jasper.ai?ref=aitoolsreview",
    affiliateCommission: "30% recurring",
    websiteUrl: "https://jasper.ai",
    features: ["50+ content templates", "Brand Voice", "SEO mode", "Plagiarism checker", "Chrome extension", "API access"],
    bestFor: ["Marketing teams", "Content agencies", "E-commerce brands", "SEO professionals"],
    badge: "Top Pick",
  },
  {
    slug: "surfer-seo",
    name: "Surfer SEO",
    tagline: "Rank higher with data-driven content optimization",
    description: "Surfer SEO analyzes top-ranking pages and tells you exactly what to write to rank on Google. It combines AI writing with real-time SERP data for content that actually ranks.",
    logo: "S",
    category: "SEO Tools",
    pricing: {
      free: false,
      startingAt: "$89/mo",
      plans: [
        { name: "Essential", price: "$89/mo", features: ["30 articles/mo", "Content Editor", "Keyword Research"] },
        { name: "Scale", price: "$129/mo", features: ["100 articles/mo", "AI writing", "Audit tool"] },
        { name: "Enterprise", price: "Custom", features: ["Unlimited", "White label", "API", "Dedicated CSM"] },
      ],
    },
    rating: 4.8,
    reviewCount: 1923,
    pros: ["Best-in-class SERP analysis", "Real-time optimization score", "Keyword research built in", "Jasper integration", "Clear actionable guidance"],
    cons: ["Expensive for small sites", "No free plan", "Data can lag", "Limited to content SEO"],
    affiliateUrl: "https://surferseo.com?ref=aitoolsreview",
    affiliateCommission: "25% recurring",
    websiteUrl: "https://surferseo.com",
    features: ["Content Editor", "SERP Analyzer", "Keyword Research", "Site Audit", "AI Outline", "NLP optimization"],
    bestFor: ["SEO professionals", "Content marketers", "Agencies", "Bloggers serious about ranking"],
    badge: "Best for SEO",
  },
  {
    slug: "writesonic",
    name: "Writesonic",
    tagline: "AI writing for everyone — free plan included",
    description: "Writesonic is one of the most capable AI writing tools with a generous free plan. It powers everything from blog posts to landing pages, product descriptions, and ads using GPT-4.",
    logo: "W",
    category: "AI Writing",
    pricing: {
      free: true,
      startingAt: "$16/mo",
      plans: [
        { name: "Free", price: "$0", features: ["10k words/mo", "ChatSonic", "100+ templates"] },
        { name: "Small Team", price: "$16/mo", features: ["Unlimited words", "GPT-4", "Brand Voice"] },
        { name: "Enterprise", price: "Custom", features: ["Custom AI", "SSO", "Dedicated support"] },
      ],
    },
    rating: 4.5,
    reviewCount: 3241,
    pros: ["Generous free plan", "GPT-4 powered", "100+ templates", "ChatSonic included", "Affordable entry price"],
    cons: ["Quality varies by template", "Word limits on free", "UI can feel cluttered", "Less precise than Jasper"],
    affiliateUrl: "https://writesonic.com?ref=aitoolsreview",
    affiliateCommission: "30% recurring",
    websiteUrl: "https://writesonic.com",
    features: ["100+ templates", "ChatSonic AI", "Brand Voice", "Bulk generation", "Zapier integration", "API"],
    bestFor: ["Freelancers", "Small businesses", "Solopreneurs", "Budget-conscious marketers"],
    badge: "Best Free Plan",
  },
  {
    slug: "copy-ai",
    name: "Copy.ai",
    tagline: "Go from prompt to pipeline with AI",
    description: "Copy.ai has evolved from a copywriting tool into a full GTM AI platform. It automates sales, marketing, and content workflows with AI — from cold emails to full campaign execution.",
    logo: "C",
    category: "AI Writing",
    pricing: {
      free: true,
      startingAt: "$36/mo",
      plans: [
        { name: "Free", price: "$0", features: ["2,000 words/mo", "90+ tools", "Chat"] },
        { name: "Pro", price: "$36/mo", features: ["Unlimited words", "5 users", "Workflows"] },
        { name: "Team", price: "$186/mo", features: ["20 users", "Advanced workflows", "API"] },
      ],
    },
    rating: 4.4,
    reviewCount: 2156,
    pros: ["Excellent free plan", "90+ copywriting tools", "Workflow automation", "Great for cold outreach", "Active community"],
    cons: ["Workflow learning curve", "Less polished than Jasper", "Inconsistent quality", "Limited SEO features"],
    affiliateUrl: "https://copy.ai?ref=aitoolsreview",
    affiliateCommission: "$50–$100 per referral",
    websiteUrl: "https://copy.ai",
    features: ["90+ AI tools", "Workflows", "Chat interface", "Bulk processing", "API access", "Integrations"],
    bestFor: ["Sales teams", "Marketing ops", "Cold email writers", "Startups"],
  },
  {
    slug: "pictory",
    name: "Pictory",
    tagline: "Turn text and scripts into professional videos instantly",
    description: "Pictory uses AI to transform blog posts, scripts, and long-form content into short branded videos. Perfect for repurposing content without any video editing experience.",
    logo: "P",
    category: "AI Video",
    pricing: {
      free: false,
      startingAt: "$19/mo",
      plans: [
        { name: "Starter", price: "$19/mo", features: ["30 videos/mo", "Text to video", "1080p export"] },
        { name: "Professional", price: "$39/mo", features: ["60 videos/mo", "Branded templates", "Highlight reel"] },
        { name: "Teams", price: "$99/mo", features: ["3 workspaces", "Unlimited brands", "Priority support"] },
      ],
    },
    rating: 4.3,
    reviewCount: 987,
    pros: ["No video editing skills needed", "Great for repurposing content", "Auto captions", "Stock library included", "Affordable"],
    cons: ["Limited customization", "AI voice sounds robotic", "No live action recording", "Export speed can be slow"],
    affiliateUrl: "https://pictory.ai?ref=aitoolsreview",
    affiliateCommission: "20% recurring",
    websiteUrl: "https://pictory.ai",
    features: ["Text to video", "Blog to video", "Auto captions", "Stock media library", "Brand kit", "Script to video"],
    bestFor: ["Content repurposers", "Social media managers", "Coaches", "Course creators"],
  },
  {
    slug: "synthesia",
    name: "Synthesia",
    tagline: "Create AI videos with human avatars in minutes",
    description: "Synthesia lets you create professional videos with realistic AI avatars and voices in 130+ languages — no camera, no studio, no actors needed. Used by 50,000+ companies including Google and Reuters.",
    logo: "SY",
    category: "AI Video",
    pricing: {
      free: false,
      startingAt: "$29/mo",
      plans: [
        { name: "Starter", price: "$29/mo", features: ["10 videos/mo", "90+ avatars", "60+ templates"] },
        { name: "Creator", price: "$89/mo", features: ["30 videos/mo", "Custom avatar", "Screen recorder"] },
        { name: "Enterprise", price: "Custom", features: ["Unlimited", "API", "SSO", "Custom avatars"] },
      ],
    },
    rating: 4.6,
    reviewCount: 1456,
    pros: ["Most realistic AI avatars", "130+ languages", "No filming needed", "Professional output", "Enterprise ready"],
    cons: ["Expensive for high volume", "Avatars can look uncanny", "No free plan", "Limited B-roll options"],
    affiliateUrl: "https://synthesia.io?ref=aitoolsreview",
    affiliateCommission: "20–30% per sale",
    websiteUrl: "https://synthesia.io",
    features: ["160+ AI avatars", "130+ languages", "Custom avatar", "Screen recorder", "API", "Brand kit"],
    bestFor: ["L&D teams", "Corporate training", "Explainer videos", "Multilingual content"],
    badge: "Best AI Avatars",
  },
  {
    slug: "descript",
    name: "Descript",
    tagline: "Edit video by editing text — the future of post-production",
    description: "Descript transcribes your video and lets you edit it like a document. Delete filler words, clone your voice, remove silences, and publish — all without touching a traditional timeline editor.",
    logo: "D",
    category: "AI Video",
    pricing: {
      free: true,
      startingAt: "$24/mo",
      plans: [
        { name: "Free", price: "$0", features: ["1 transcription hr/mo", "Basic editing", "720p export"] },
        { name: "Creator", price: "$24/mo", features: ["10 hrs/mo", "AI features", "4K export"] },
        { name: "Business", price: "$40/mo", features: ["Unlimited", "Team features", "Priority support"] },
      ],
    },
    rating: 4.7,
    reviewCount: 2034,
    pros: ["Revolutionary editing workflow", "Best-in-class transcription", "Filler word removal", "Voice clone", "Great for podcasts"],
    cons: ["Resource intensive", "Collaboration can lag", "Learning curve", "Some AI features hit or miss"],
    affiliateUrl: "https://descript.com?ref=aitoolsreview",
    affiliateCommission: "15–20% recurring",
    websiteUrl: "https://descript.com",
    features: ["Text-based editing", "AI transcription", "Filler word removal", "Overdub voice clone", "Screen recording", "Podcast publishing"],
    bestFor: ["Podcasters", "YouTubers", "Video editors", "Content creators"],
  },
  {
    slug: "canva-pro",
    name: "Canva Pro",
    tagline: "Design anything. Publish anywhere.",
    description: "Canva Pro supercharges the world's most popular design tool with AI features, brand kits, unlimited storage, background remover, and thousands of premium templates. The go-to design tool for non-designers.",
    logo: "CA",
    category: "AI Design",
    pricing: {
      free: true,
      startingAt: "$15/mo",
      plans: [
        { name: "Free", price: "$0", features: ["250,000+ templates", "5GB storage", "Basic tools"] },
        { name: "Pro", price: "$15/mo", features: ["100M+ assets", "Brand Kit", "Background remover", "Magic Resize"] },
        { name: "Teams", price: "$10/mo/user", features: ["All Pro features", "Collaboration", "Admin controls"] },
      ],
    },
    rating: 4.8,
    reviewCount: 8923,
    pros: ["Incredibly easy to use", "Massive template library", "AI image generation", "Brand Kit", "Best value in design"],
    cons: ["Not for professional designers", "Limited typography control", "Exports can compress quality", "AI features still maturing"],
    affiliateUrl: "https://canva.com?ref=aitoolsreview",
    affiliateCommission: "Up to $36 per subscription",
    websiteUrl: "https://canva.com",
    features: ["Magic Write AI", "Text to Image", "Background Remover", "Magic Resize", "Brand Kit", "100M+ assets"],
    bestFor: ["Small businesses", "Social media managers", "Non-designers", "Marketers", "Educators"],
    badge: "Most Popular",
  },
  {
    slug: "grammarly",
    name: "Grammarly",
    tagline: "Write with confidence — grammar, style, and tone in one",
    description: "Grammarly is the world's leading AI writing assistant, helping 30 million people write clearer, mistake-free content. From emails to essays, it catches errors and suggests improvements in real time across every platform.",
    logo: "G",
    category: "AI Writing",
    pricing: {
      free: true,
      startingAt: "$12/mo",
      plans: [
        { name: "Free", price: "$0", features: ["Grammar checks", "Spelling", "Basic tone"] },
        { name: "Premium", price: "$12/mo", features: ["Style suggestions", "Plagiarism checker", "Full-sentence rewrites"] },
        { name: "Business", price: "$15/mo/user", features: ["Team dashboard", "Style guide", "Analytics"] },
      ],
    },
    rating: 4.6,
    reviewCount: 12847,
    pros: ["Works everywhere", "Excellent free plan", "Real-time suggestions", "Tone detection", "Plagiarism checker in Premium"],
    cons: ["Premium needed for full value", "Can over-suggest changes", "Privacy concerns for sensitive docs", "Occasional false positives"],
    affiliateUrl: "https://grammarly.com?ref=aitoolsreview",
    affiliateCommission: "$0.20 free / $20 premium signup",
    websiteUrl: "https://grammarly.com",
    features: ["Grammar & spelling", "Style suggestions", "Tone detector", "Plagiarism checker", "Full rewrites", "Works everywhere"],
    bestFor: ["Students", "Professionals", "Non-native English speakers", "Anyone who writes"],
    badge: "Editor's Choice",
  },
  {
    slug: "hostinger",
    name: "Hostinger",
    tagline: "Fast, affordable hosting powered by AI website builder",
    description: "Hostinger offers blazing-fast web hosting with an AI website builder that creates a professional site in minutes. At $2.99/mo it's the best value hosting on the market, backed by 24/7 support.",
    logo: "H",
    category: "Web Hosting",
    pricing: {
      free: false,
      startingAt: "$2.99/mo",
      plans: [
        { name: "Premium", price: "$2.99/mo", features: ["100 websites", "100GB SSD", "Free domain", "SSL"] },
        { name: "Business", price: "$3.99/mo", features: ["200GB SSD", "Daily backups", "CDN"] },
        { name: "Cloud", price: "$9.99/mo", features: ["300GB SSD", "Dedicated resources", "Priority support"] },
      ],
    },
    rating: 4.5,
    reviewCount: 6234,
    pros: ["Cheapest quality hosting", "AI website builder", "Free domain included", "Fast load times", "24/7 live chat"],
    cons: ["Renewal prices higher", "No US data center on cheapest plan", "Limited staging environment", "Phone support not available"],
    affiliateUrl: "https://hostinger.com?ref=aitoolsreview",
    affiliateCommission: "60% per sale",
    websiteUrl: "https://hostinger.com",
    features: ["AI Website Builder", "Free domain", "Free SSL", "LiteSpeed servers", "WordPress one-click", "99.9% uptime"],
    bestFor: ["Beginners", "Small businesses", "Bloggers", "Budget-conscious site owners"],
  },
  {
    slug: "chatgpt",
    name: "ChatGPT",
    tagline: "The AI assistant that started it all — now more powerful than ever",
    description: "ChatGPT by OpenAI is the world's most widely used AI assistant. From writing and coding to analysis and brainstorming, GPT-4o handles virtually any task. The free plan is generous, and Plus unlocks the most capable models available.",
    logo: "GP",
    category: "AI Writing",
    pricing: {
      free: true,
      startingAt: "$20/mo",
      plans: [
        { name: "Free", price: "$0", features: ["GPT-4o mini", "Limited GPT-4o", "DALL-E image gen", "Web browsing"] },
        { name: "Plus", price: "$20/mo", features: ["Full GPT-4o access", "Advanced data analysis", "Custom GPTs", "Image generation"] },
        { name: "Team", price: "$25/mo/user", features: ["All Plus features", "Admin console", "Higher limits", "Data privacy"] },
      ],
    },
    rating: 4.8,
    reviewCount: 45231,
    pros: ["Most capable AI model available", "Versatile — writing, coding, analysis", "Generous free plan", "Huge plugin/GPT ecosystem", "Best for brainstorming"],
    cons: ["Can hallucinate facts", "Not built for marketing workflows", "No brand voice training", "Context window limits on free"],
    affiliateUrl: "https://chat.openai.com?ref=aitoolsreview",
    affiliateCommission: "N/A — direct signup",
    websiteUrl: "https://chat.openai.com",
    features: ["GPT-4o model", "DALL-E image generation", "Code interpreter", "Web browsing", "Custom GPTs", "API access"],
    bestFor: ["Developers", "Researchers", "Writers", "Anyone needing a general-purpose AI"],
    badge: "Most Used AI",
  },
  {
    slug: "claude-ai",
    name: "Claude AI",
    tagline: "The safest, most thoughtful AI assistant for long-form work",
    description: "Claude by Anthropic is built for nuanced, long-form tasks — writing, analysis, coding, and research. It has the longest context window of any mainstream AI and is known for being unusually thoughtful and accurate. Ideal for document analysis and in-depth writing.",
    logo: "CL",
    category: "AI Writing",
    pricing: {
      free: true,
      startingAt: "$20/mo",
      plans: [
        { name: "Free", price: "$0", features: ["Claude 3.5 Sonnet", "Limited messages", "File uploads", "Web search"] },
        { name: "Pro", price: "$20/mo", features: ["5x more usage", "Claude Opus", "Priority access", "Projects"] },
        { name: "Team", price: "$25/mo/user", features: ["All Pro features", "Admin tools", "Expanded context", "Collaboration"] },
      ],
    },
    rating: 4.8,
    reviewCount: 18750,
    pros: ["Longest context window", "Excellent at long-form writing", "Very accurate and nuanced", "Great for document analysis", "Strong coding ability"],
    cons: ["Fewer integrations than ChatGPT", "No image generation built in", "Usage limits on free plan", "Less plugin ecosystem"],
    affiliateUrl: "https://claude.ai?ref=aitoolsreview",
    affiliateCommission: "N/A — direct signup",
    websiteUrl: "https://claude.ai",
    features: ["200k token context", "File & doc analysis", "Artifacts (live code)", "Projects", "Web search", "API access"],
    bestFor: ["Writers", "Researchers", "Analysts", "Developers", "Anyone working with long documents"],
  },
  {
    slug: "notion-ai",
    name: "Notion AI",
    tagline: "AI built right into your workspace — write, summarize, and organize",
    description: "Notion AI brings AI directly into your notes, docs, and wikis. Summarize meeting notes, draft content, translate pages, and generate action items — all without leaving Notion. The best AI tool for teams already using Notion.",
    logo: "NO",
    category: "AI Productivity",
    pricing: {
      free: false,
      startingAt: "$10/mo",
      plans: [
        { name: "AI Add-on", price: "$10/mo/user", features: ["Unlimited AI", "All Notion plans", "Summarize docs", "Draft content"] },
        { name: "Plus + AI", price: "$18/mo/user", features: ["Full Notion Plus", "AI included", "Unlimited pages", "Guests"] },
        { name: "Business + AI", price: "$25/mo/user", features: ["Advanced permissions", "SAML SSO", "Audit log", "Priority support"] },
      ],
    },
    rating: 4.5,
    reviewCount: 9840,
    pros: ["Seamlessly embedded in workflow", "Excellent summarization", "Translates docs instantly", "Action item extraction", "Works on any Notion page"],
    cons: ["Requires Notion subscription", "Not a standalone AI tool", "Can be slow on large docs", "Less powerful than dedicated AI writers"],
    affiliateUrl: "https://notion.so/product/ai?ref=aitoolsreview",
    affiliateCommission: "Variable",
    websiteUrl: "https://notion.so/product/ai",
    features: ["AI writing in docs", "Summarize pages", "Translate content", "Generate action items", "Auto-fill databases", "Ask AI about your docs"],
    bestFor: ["Notion users", "Remote teams", "Project managers", "Knowledge workers"],
  },
  {
    slug: "rytr",
    name: "Rytr",
    tagline: "The most affordable AI writing tool with 40+ use cases",
    description: "Rytr is a budget-friendly AI writing assistant with 40+ use cases, 30+ languages, and a generous free plan. It's not the most powerful AI writer, but for basic copy — emails, social posts, product descriptions — it gets the job done at a fraction of the cost.",
    logo: "RY",
    category: "AI Writing",
    pricing: {
      free: true,
      startingAt: "$9/mo",
      plans: [
        { name: "Free", price: "$0", features: ["10k chars/month", "40+ use cases", "30+ languages"] },
        { name: "Saver", price: "$9/mo", features: ["100k chars/month", "Premium use cases", "Plagiarism checker"] },
        { name: "Unlimited", price: "$29/mo", features: ["Unlimited chars", "Dedicated account manager", "Custom use case"] },
      ],
    },
    rating: 4.1,
    reviewCount: 4210,
    pros: ["Very affordable", "40+ use cases", "30+ languages", "Simple interface", "Good for basic copy"],
    cons: ["Lower output quality than Jasper/Writesonic", "Limited customization", "No advanced AI models", "Basic template library"],
    affiliateUrl: "https://rytr.me?ref=aitoolsreview",
    affiliateCommission: "30% recurring",
    websiteUrl: "https://rytr.me",
    features: ["40+ use cases", "30+ languages", "Plagiarism checker", "Chrome extension", "API access", "Tone selector"],
    bestFor: ["Budget-conscious users", "Beginners", "Basic copywriting needs", "Non-English speakers"],
  },
  {
    slug: "ahrefs",
    name: "Ahrefs",
    tagline: "The most powerful SEO toolkit for serious marketers",
    description: "Ahrefs is the gold standard for SEO research — backlink analysis, keyword research, site audits, and competitor intelligence. Used by SEO professionals worldwide, it provides the deepest data available for building organic search strategies.",
    logo: "AH",
    category: "SEO Tools",
    pricing: {
      free: false,
      startingAt: "$129/mo",
      plans: [
        { name: "Lite", price: "$129/mo", features: ["5 projects", "6 months history", "Site Explorer", "Keywords Explorer"] },
        { name: "Standard", price: "$249/mo", features: ["20 projects", "2 years history", "Content Explorer", "Rank Tracker"] },
        { name: "Advanced", price: "$449/mo", features: ["50 projects", "5 years history", "Web Explorer", "API"] },
      ],
    },
    rating: 4.8,
    reviewCount: 7823,
    pros: ["Best backlink database", "Deep keyword research", "Excellent competitor analysis", "Site audit is thorough", "Constant updates"],
    cons: ["Expensive for beginners", "Steep learning curve", "No free plan", "Can be overwhelming"],
    affiliateUrl: "https://ahrefs.com?ref=aitoolsreview",
    affiliateCommission: "Variable — contact team",
    websiteUrl: "https://ahrefs.com",
    features: ["Site Explorer", "Keywords Explorer", "Content Explorer", "Site Audit", "Rank Tracker", "Backlink checker"],
    bestFor: ["SEO professionals", "Digital marketing agencies", "Enterprise teams", "Serious bloggers"],
    badge: "SEO Standard",
  },
  {
    slug: "semrush",
    name: "SEMrush",
    tagline: "All-in-one SEO, PPC, and content marketing platform",
    description: "SEMrush is the most comprehensive digital marketing platform available — covering SEO, PPC, social media, content marketing, and competitor research in one tool. The go-to choice for agencies managing multiple clients.",
    logo: "SM",
    category: "SEO Tools",
    pricing: {
      free: false,
      startingAt: "$139/mo",
      plans: [
        { name: "Pro", price: "$139/mo", features: ["5 projects", "500 keywords", "Site audit", "Position tracking"] },
        { name: "Guru", price: "$249/mo", features: ["15 projects", "1,500 keywords", "Content Marketing", "Historical data"] },
        { name: "Business", price: "$499/mo", features: ["40 projects", "5,000 keywords", "API", "White label"] },
      ],
    },
    rating: 4.7,
    reviewCount: 11240,
    pros: ["Most features of any SEO tool", "Excellent PPC research", "Content marketing toolkit", "Local SEO features", "Great for agencies"],
    cons: ["Very expensive", "Interface can be overwhelming", "Some data less accurate than Ahrefs", "No free plan"],
    affiliateUrl: "https://semrush.com?ref=aitoolsreview",
    affiliateCommission: "$200 per sale",
    websiteUrl: "https://semrush.com",
    features: ["Keyword research", "Backlink audit", "Site crawl", "PPC research", "Social media toolkit", "Content analyzer"],
    bestFor: ["Digital marketing agencies", "Enterprise SEO teams", "PPC managers", "Multi-channel marketers"],
  },
  {
    slug: "runway-ml",
    name: "Runway ML",
    tagline: "The most advanced AI video generation and editing platform",
    description: "Runway ML is the leading AI video generation platform — used by Hollywood studios and indie creators alike. Generate video from text, animate images, remove backgrounds in real time, and access cutting-edge video AI models before anyone else.",
    logo: "RW",
    category: "AI Video",
    pricing: {
      free: true,
      startingAt: "$15/mo",
      plans: [
        { name: "Free", price: "$0", features: ["125 credits", "Gen-3 Alpha", "3 projects", "720p export"] },
        { name: "Standard", price: "$15/mo", features: ["625 credits/mo", "Full Gen-3", "Watermark removal", "4K upscaling"] },
        { name: "Pro", price: "$35/mo", features: ["2,250 credits/mo", "Custom voices", "Teams", "Priority"] },
      ],
    },
    rating: 4.6,
    reviewCount: 6540,
    pros: ["Best AI video generation quality", "Used by Hollywood professionals", "Constantly improving models", "Great for creative work", "Real-time green screen"],
    cons: ["Credit system can get expensive", "Learning curve for advanced features", "Video length limits", "Renders can be slow"],
    affiliateUrl: "https://runwayml.com?ref=aitoolsreview",
    affiliateCommission: "20% recurring",
    websiteUrl: "https://runwayml.com",
    features: ["Text to video", "Image to video", "Video inpainting", "Background removal", "Motion brush", "4K upscaling"],
    bestFor: ["Creative directors", "Filmmakers", "VFX artists", "Social media creators", "Advertisers"],
    badge: "Most Advanced",
  },
  {
    slug: "heygen",
    name: "HeyGen",
    tagline: "Create talking avatar videos from text in minutes",
    description: "HeyGen makes it easy to create professional talking-head videos with AI avatars and voices. Popular for product demos, marketing videos, and personalized outreach at scale. The instant avatar feature lets you clone yourself in minutes.",
    logo: "HG",
    category: "AI Video",
    pricing: {
      free: true,
      startingAt: "$29/mo",
      plans: [
        { name: "Free", price: "$0", features: ["1 credit/month", "3 min video", "Watermark", "Basic avatars"] },
        { name: "Creator", price: "$29/mo", features: ["15 credits/mo", "No watermark", "Custom avatar", "Voice clone"] },
        { name: "Business", price: "$89/mo", features: ["30 credits/mo", "Priority rendering", "API", "Team seats"] },
      ],
    },
    rating: 4.5,
    reviewCount: 5120,
    pros: ["Easy instant avatar creation", "Good video quality", "Voice cloning included", "Personalized video at scale", "Lots of avatar options"],
    cons: ["Credits go fast", "Watermark on free plan", "Avatars still look AI", "Limited B-roll options"],
    affiliateUrl: "https://heygen.com?ref=aitoolsreview",
    affiliateCommission: "25% recurring",
    websiteUrl: "https://heygen.com",
    features: ["AI avatars", "Voice cloning", "Instant avatar", "Personalized video", "API", "130+ languages"],
    bestFor: ["Sales teams", "Course creators", "Marketing teams", "Agencies doing personalized outreach"],
  },
  {
    slug: "midjourney",
    name: "Midjourney",
    tagline: "The world's best AI image generator — stunning results every time",
    description: "Midjourney produces the most visually stunning AI-generated images available. Used by designers, artists, marketers, and creatives worldwide, it consistently outperforms every other image generator on photorealism and artistic quality.",
    logo: "MJ",
    category: "AI Design",
    pricing: {
      free: false,
      startingAt: "$10/mo",
      plans: [
        { name: "Basic", price: "$10/mo", features: ["~200 images/mo", "3 concurrent jobs", "Discord access"] },
        { name: "Standard", price: "$30/mo", features: ["15hr fast GPU", "Unlimited relaxed", "Stealth mode"] },
        { name: "Pro", price: "$60/mo", features: ["30hr fast GPU", "Stealth mode", "12 concurrent jobs"] },
      ],
    },
    rating: 4.9,
    reviewCount: 32100,
    pros: ["Best image quality of any AI generator", "Incredible artistic range", "Huge community and prompt library", "Fast generation", "Constantly improving"],
    cons: ["Runs through Discord (unusual UX)", "No free plan", "Copyright questions remain", "Prompt crafting has a learning curve"],
    affiliateUrl: "https://midjourney.com?ref=aitoolsreview",
    affiliateCommission: "N/A — no affiliate program",
    websiteUrl: "https://midjourney.com",
    features: ["Photorealistic images", "Artistic styles", "Image variations", "Upscaling", "Inpainting", "Web interface"],
    bestFor: ["Designers", "Artists", "Marketers", "Content creators", "Anyone needing premium visuals"],
    badge: "Best Image Quality",
  },
  {
    slug: "elevenlabs",
    name: "ElevenLabs",
    tagline: "The most realistic AI voice generator on the market",
    description: "ElevenLabs creates the most natural-sounding AI voices available — indistinguishable from real humans in many cases. Used for podcasts, audiobooks, YouTube videos, and voice cloning. The voice cloning feature can replicate any voice from a short sample.",
    logo: "EL",
    category: "AI Voice",
    pricing: {
      free: true,
      startingAt: "$5/mo",
      plans: [
        { name: "Free", price: "$0", features: ["10k chars/mo", "3 custom voices", "Commercial use"] },
        { name: "Starter", price: "$5/mo", features: ["30k chars/mo", "10 custom voices", "Voice cloning"] },
        { name: "Creator", price: "$22/mo", features: ["100k chars/mo", "30 custom voices", "Professional clone"] },
      ],
    },
    rating: 4.8,
    reviewCount: 14320,
    pros: ["Most realistic AI voices", "Excellent voice cloning", "Wide language support", "Great for content creators", "Easy to use"],
    cons: ["Usage limits on cheap plans", "Voice cloning can raise ethical questions", "Price scales quickly at volume", "Occasional robotic artifacts"],
    affiliateUrl: "https://elevenlabs.io?ref=aitoolsreview",
    affiliateCommission: "22% recurring",
    websiteUrl: "https://elevenlabs.io",
    features: ["Voice cloning", "Text to speech", "Voice design", "Dubbing", "API", "29+ languages"],
    bestFor: ["Podcasters", "YouTubers", "Audiobook creators", "Game developers", "Content creators"],
    badge: "Best AI Voice",
  },
  {
    slug: "adobe-firefly",
    name: "Adobe Firefly",
    tagline: "Adobe's AI image generator — commercially safe and Photoshop-native",
    description: "Adobe Firefly is built into Photoshop, Illustrator, and Express — making it the most practical AI image generator for professional designers. All images are commercially safe (trained on licensed content), which matters for business use.",
    logo: "AF",
    category: "AI Design",
    pricing: {
      free: true,
      startingAt: "$4.99/mo",
      plans: [
        { name: "Free", price: "$0", features: ["25 generative credits/mo", "Basic features", "Firefly web app"] },
        { name: "Premium", price: "$4.99/mo", features: ["100 credits/mo", "Firefly web app", "Priority access"] },
        { name: "Creative Cloud", price: "$54.99/mo", features: ["Photoshop + Illustrator", "Unlimited credits", "Full Adobe suite"] },
      ],
    },
    rating: 4.4,
    reviewCount: 8930,
    pros: ["Commercially safe images", "Native in Photoshop/Illustrator", "Generative fill is incredible", "No legal risk", "Improving rapidly"],
    cons: ["Not as artistic as Midjourney", "Limited credits on cheap plans", "Full value requires Creative Cloud", "Slower than competitors"],
    affiliateUrl: "https://adobe.com/products/firefly?ref=aitoolsreview",
    affiliateCommission: "85% first month / 8.33% recurring",
    websiteUrl: "https://firefly.adobe.com",
    features: ["Text to image", "Generative fill", "Generative expand", "Text effects", "Recolor vectors", "Photoshop integration"],
    bestFor: ["Professional designers", "Agencies", "Brands needing commercial safety", "Photoshop users"],
  },
  {
    slug: "otter-ai",
    name: "Otter.ai",
    tagline: "AI meeting notes and transcription — never miss what was said",
    description: "Otter.ai automatically joins your Zoom, Meet, and Teams calls, transcribes everything in real time, generates summaries, and extracts action items. The best way to eliminate manual note-taking from meetings forever.",
    logo: "OT",
    category: "AI Productivity",
    pricing: {
      free: true,
      startingAt: "$16.99/mo",
      plans: [
        { name: "Basic", price: "$0", features: ["300 min/mo transcription", "Otter AI chat", "Meeting import"] },
        { name: "Pro", price: "$16.99/mo", features: ["1,200 min/mo", "Advanced search", "Export to Notion/Slack"] },
        { name: "Business", price: "$30/mo/user", features: ["6,000 min/mo", "Admin dashboard", "Vocabulary customization"] },
      ],
    },
    rating: 4.4,
    reviewCount: 7650,
    pros: ["Auto-joins meetings", "Accurate real-time transcription", "Good action item extraction", "Integrates with Zoom/Meet/Teams", "Searchable transcripts"],
    cons: ["Accuracy drops with accents", "Can feel intrusive to guests", "Storage limits on free", "AI summaries sometimes miss context"],
    affiliateUrl: "https://otter.ai?ref=aitoolsreview",
    affiliateCommission: "Variable",
    websiteUrl: "https://otter.ai",
    features: ["Real-time transcription", "Meeting summaries", "Action item extraction", "Zoom/Meet/Teams integration", "Otter AI chat", "Speaker identification"],
    bestFor: ["Remote teams", "Sales professionals", "Managers", "Journalists", "Students"],
  },
  {
    slug: "deepl",
    name: "DeepL",
    tagline: "The most accurate AI translator — better than Google Translate",
    description: "DeepL produces translations that are consistently more natural and accurate than Google Translate, especially for business content. Supports 30+ languages with context-aware nuance that other tools miss. The go-to translation tool for global businesses.",
    logo: "DL",
    category: "AI Productivity",
    pricing: {
      free: true,
      startingAt: "$8.74/mo",
      plans: [
        { name: "Free", price: "$0", features: ["500k chars/mo", "30+ languages", "Document translation"] },
        { name: "Starter", price: "$8.74/mo", features: ["1 user", "Unlimited text", "10 docs/mo"] },
        { name: "Advanced", price: "$28.74/mo", features: ["3 users", "Unlimited docs", "Glossary", "API"] },
      ],
    },
    rating: 4.7,
    reviewCount: 19400,
    pros: ["Most accurate AI translator", "Natural-sounding output", "Business-quality translations", "Document translation included", "Privacy-focused"],
    cons: ["Fewer languages than Google", "Premium needed for volume", "No real-time voice translation", "API costs add up"],
    affiliateUrl: "https://deepl.com?ref=aitoolsreview",
    affiliateCommission: "Variable",
    websiteUrl: "https://deepl.com",
    features: ["30+ languages", "Document translation", "Glossary", "API", "Chrome extension", "Desktop app"],
    bestFor: ["Global businesses", "Translators", "Content teams", "Non-native English speakers", "International marketers"],
  },
  {
    slug: "murf-ai",
    name: "Murf.ai",
    tagline: "Studio-quality AI voiceovers in minutes — no mic needed",
    description: "Murf.ai is a professional AI voice generator used by thousands of content creators, course builders, and marketers. Choose from 120+ voices in 20+ languages, control pitch and speed, and sync audio to video — all in the browser. The best alternative to expensive voice-over artists.",
    logo: "MU",
    category: "AI Voice",
    pricing: {
      free: true,
      startingAt: "$19/mo",
      plans: [
        { name: "Free", price: "$0", features: ["10 mins voice gen", "120+ voices", "No watermark"] },
        { name: "Creator", price: "$19/mo", features: ["2 hrs/mo", "All voices", "Voice changer", "Downloads"] },
        { name: "Business", price: "$26/mo", features: ["4 hrs/mo", "Team sharing", "Custom pronunciation", "API"] },
      ],
    },
    rating: 4.6,
    reviewCount: 5840,
    pros: ["120+ studio-quality voices", "Easy video sync", "No recording equipment needed", "Great for courses and explainers", "Affordable pricing"],
    cons: ["Free plan very limited", "Less natural than ElevenLabs", "No real-time voice cloning", "Voice variety can sound similar"],
    affiliateUrl: "https://murf.ai?ref=aitoolsreview",
    affiliateCommission: "20% recurring",
    websiteUrl: "https://murf.ai",
    features: ["120+ AI voices", "20+ languages", "Voice changer", "Video sync", "Pitch & speed control", "Team collaboration"],
    bestFor: ["Course creators", "Explainer video makers", "Podcasters", "Marketers", "E-learning developers"],
  },
  {
    slug: "invideo-ai",
    name: "InVideo AI",
    tagline: "Turn any idea or blog post into a polished video with AI",
    description: "InVideo AI lets you create professional videos from text prompts, scripts, or blog posts in minutes. With 5,000+ templates, AI voiceover, and a massive stock media library, it's the fastest way to produce social media and marketing videos without any editing skills.",
    logo: "IV",
    category: "AI Video",
    pricing: {
      free: true,
      startingAt: "$20/mo",
      plans: [
        { name: "Free", price: "$0", features: ["10 min video/wk", "4 exports/wk", "Watermark", "10GB storage"] },
        { name: "Plus", price: "$20/mo", features: ["60 AI videos/mo", "No watermark", "80 exports", "AI script"] },
        { name: "Max", price: "$48/mo", features: ["120 AI videos/mo", "Unlimited exports", "Priority support", "120 voice clones"] },
      ],
    },
    rating: 4.5,
    reviewCount: 8930,
    pros: ["Easiest text-to-video workflow", "5,000+ templates", "Built-in stock library", "AI script generator", "Good free plan"],
    cons: ["Watermark on free", "Less cinematic than Runway", "AI voice can sound robotic", "Export times vary"],
    affiliateUrl: "https://invideo.io?ref=aitoolsreview",
    affiliateCommission: "30% recurring",
    websiteUrl: "https://invideo.io",
    features: ["Text to video", "5,000+ templates", "AI voiceover", "Stock media library", "Brand kit", "Auto subtitles"],
    bestFor: ["Social media managers", "Content creators", "Marketers", "Small businesses", "YouTubers"],
    badge: "Best Value Video AI",
  },
  {
    slug: "gamma",
    name: "Gamma",
    tagline: "Create stunning presentations, docs, and websites with AI",
    description: "Gamma uses AI to generate beautiful presentations, documents, and webpages from a simple prompt in seconds. No design skills required — just describe what you need and Gamma builds a polished deck with smart layouts, imagery, and formatting that looks better than most human-made slides.",
    logo: "GA",
    category: "AI Productivity",
    pricing: {
      free: true,
      startingAt: "$10/mo",
      plans: [
        { name: "Free", price: "$0", features: ["400 AI credits", "Unlimited decks", "Gamma branding", "Export PDF"] },
        { name: "Plus", price: "$10/mo", features: ["Unlimited AI", "Custom branding", "Analytics", "No watermark"] },
        { name: "Pro", price: "$20/mo", features: ["Priority AI", "Custom domains", "Password protection", "Advanced analytics"] },
      ],
    },
    rating: 4.6,
    reviewCount: 6120,
    pros: ["Stunning designs instantly", "Works for slides, docs, and websites", "AI layout intelligence", "Easy sharing and embedding", "Great free plan"],
    cons: ["Less control than PowerPoint", "AI sometimes misses the brief", "Custom branding needs paid plan", "Template variety still growing"],
    affiliateUrl: "https://gamma.app?ref=aitoolsreview",
    affiliateCommission: "20% recurring",
    websiteUrl: "https://gamma.app",
    features: ["AI presentation generation", "Smart layouts", "One-click themes", "Web publishing", "Analytics", "PDF/PPT export"],
    bestFor: ["Sales teams", "Founders pitching investors", "Educators", "Marketers", "Anyone who hates making slides"],
    badge: "Best AI Presentations",
  },
  {
    slug: "perplexity-ai",
    name: "Perplexity AI",
    tagline: "The AI search engine that cites its sources",
    description: "Perplexity AI is a next-generation search engine powered by AI — it gives you direct answers to complex questions with cited sources, not a list of links. It's the fastest way to research any topic with real-time web data, and it's quickly replacing traditional search for power users.",
    logo: "PX",
    category: "AI Writing",
    pricing: {
      free: true,
      startingAt: "$20/mo",
      plans: [
        { name: "Free", price: "$0", features: ["Unlimited searches", "GPT-3.5 base", "5 Pro searches/day", "File uploads"] },
        { name: "Pro", price: "$20/mo", features: ["600+ Pro searches/day", "GPT-4o / Claude / Gemini", "Image generation", "API credits"] },
      ],
    },
    rating: 4.7,
    reviewCount: 21400,
    pros: ["Always cites sources", "Real-time web data", "Multiple AI models", "Great for research", "Fast and clean UI"],
    cons: ["Less creative than ChatGPT", "Not built for content creation", "Pro searches limited on free", "Can over-simplify complex topics"],
    affiliateUrl: "https://perplexity.ai?ref=aitoolsreview",
    affiliateCommission: "Variable — partner program",
    websiteUrl: "https://perplexity.ai",
    features: ["AI-powered search", "Cited sources", "Real-time web data", "GPT-4o / Claude / Gemini", "File upload", "Image generation"],
    bestFor: ["Researchers", "Students", "Journalists", "Anyone fact-checking", "Power search users"],
    badge: "Best AI Search",
  },
  {
    slug: "loom",
    name: "Loom",
    tagline: "Record, share, and summarize videos — async communication reimagined",
    description: "Loom lets you record your screen and camera instantly, then share with a link. AI automatically generates transcripts, summaries, and action items from every video. The go-to tool for remote teams replacing meetings with async video messages.",
    logo: "LO",
    category: "AI Productivity",
    pricing: {
      free: true,
      startingAt: "$15/mo",
      plans: [
        { name: "Starter", price: "$0", features: ["25 videos", "5 min limit", "720p", "AI summaries"] },
        { name: "Business", price: "$15/mo/user", features: ["Unlimited videos", "No time limit", "4K", "Custom branding"] },
        { name: "Business + AI", price: "$20/mo/user", features: ["All Business features", "AI chapters", "Filler word removal", "AI tasks"] },
      ],
    },
    rating: 4.7,
    reviewCount: 14280,
    pros: ["Fastest way to record and share", "Excellent AI summaries", "Works everywhere", "Viewer reactions and comments", "Great for remote teams"],
    cons: ["25 video limit on free", "AI features cost extra", "5 min limit on free", "Video storage expires on free"],
    affiliateUrl: "https://loom.com?ref=aitoolsreview",
    affiliateCommission: "15% recurring",
    websiteUrl: "https://loom.com",
    features: ["Screen + cam recording", "AI summaries", "AI transcripts", "Instant sharing", "Viewer analytics", "Slack/Notion integration"],
    bestFor: ["Remote teams", "Product managers", "Developers", "Sales teams", "Customer success"],
  },
  {
    slug: "frase-io",
    name: "Frase.io",
    tagline: "Research, write, and optimize SEO content in one workflow",
    description: "Frase combines AI writing with SEO research — it analyzes the top-ranking pages for any keyword, builds an SEO brief automatically, then helps you write and optimize content to outrank them. The fastest end-to-end SEO content workflow available.",
    logo: "FR",
    category: "SEO Tools",
    pricing: {
      free: false,
      startingAt: "$15/mo",
      plans: [
        { name: "Solo", price: "$15/mo", features: ["4 articles/mo", "SEO research", "AI writing", "Content scoring"] },
        { name: "Basic", price: "$45/mo", features: ["30 articles/mo", "Unlimited queries", "SERP analysis"] },
        { name: "Team", price: "$115/mo", features: ["Unlimited articles", "3 users", "API", "Custom AI model"] },
      ],
    },
    rating: 4.5,
    reviewCount: 3760,
    pros: ["Best SERP brief generation", "AI writing built in", "Content scoring against competitors", "Great keyword clustering", "Affordable entry price"],
    cons: ["Article limits on lower plans", "AI writing quality inconsistent", "Less data depth than Ahrefs", "UI can feel cramped"],
    affiliateUrl: "https://frase.io?ref=aitoolsreview",
    affiliateCommission: "30% recurring",
    websiteUrl: "https://frase.io",
    features: ["SERP analysis", "AI content briefs", "AI writing assistant", "Content scoring", "Keyword research", "Topic clusters"],
    bestFor: ["SEO content writers", "Bloggers", "Content agencies", "In-house SEO teams", "Freelance writers"],
  },
]

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug)
}

export function getToolsByCategory(category: string): Tool[] {
  return tools.filter((t) => t.category === category)
}

export const categories = [...new Set(tools.map((t) => t.category))]
